### ISSUE TITLE
dotfile that are not .file but elsewhere ?

### ISSUE THREAD

**Issue by psic** [ellipsis/ellipsis#101]
Lot of my dotfiles are in ~/config folder or in my /mail folder or elsewhere. Is ellipsis handle symlink to those file. It seems,for instance, when I add to my package a file in the /mail/.../.../../myfile , it copy file to my home folder, and make a symlink to it. But the file is no longer in its original directory.

**Comment by groggemans** [comment]
Hey psic

A lot of the build in commands to handle files are made with the simplest setups in mind. For more advanced use-cases you'd have to use a custom ellipsis.sh file and do things manually.

You can take a look at one of the example packages from the package index; http://docs.ellipsis.sh/en/master/pkgindex/

Kind regards
Gertjan

**Comment by groggemans** [comment]
@psic 

I'm going to close this issue, don't hesitate to reach out again if you have further questions.
