### ISSUE TITLE
Use ellipsis.sh with another shell

### ISSUE THREAD

**Issue by shadowrylander** [ellipsis/ellipsis#102]
Hello!

Would it be possible to set up the `ellipsis.sh` file using another shell, such as the bash-wards compatible, python-based `xonsh`? If so, would the function implementations be the same, such as for `pkg.install(){}`?

Thank you kindly for the help!

**Comment by zeekay** [comment]
Unfamiliar with `xosh`, but might work natively if backwards compatible with bash. Welcome to fork for `xonsh` as well!

**Comment by shadowrylander** [comment]
By natively, would you happen to mean the functions? As far as I know, their function are primarily python-based, so I don't think that would work.

**Comment by groggemans** [comment]
@shadowrylander Just to confirm, Ellipsis is always running in Bash, that is defined by the shebang at the top of the bin file;
https://github.com/ellipsis/ellipsis/blob/63846f1aa4e84467095ceefa8fc597899865dfd2/bin/ellipsis#L1

The hooks are processed by sourcing the ellipsis.sh file, so these functions are actually executed from/in Bash and should thus be valid Bash code.

So whatever shell you are using, Ellipsis still runs/needs Bash, and ellipsis.sh files should also be valid Bash.
You could implement the actual hooks in python if you want, that would just require you to use a bash wrapper function that executes the python code.

Hope that helps if it wasn't already clear. I'll be closing the issue, but feel free to let me know if additional info is needed.

**Comment by shadowrylander** [comment]
Yep! Sounds good to me! Thanks for the clarification!
