### ISSUE TITLE
remove dependency on 'rev'

### ISSUE THREAD

**Issue by r4lv** [ellipsis/ellipsis#103]
Dear all,

I noticed a minor thing which breaks on a few systems I use — at one single location in the codebase, you are using the external tool `rev`, which is part of [util-linux](https://github.com/karelzak/util-linux/blob/master/text-utils/rev.c):

https://github.com/ellipsis/ellipsis/blob/e6fa1e7c5933990fafcbe99b1578ccd1dffc5c9b/src/pkg.bash#L33-L36

On systems running opkg/[Entware](https://github.com/Entware/Entware), `rev` is not available. What is your opinion on replacing `rev` with a bash-only solution? Happy to submit a PR!

And thank you for such a fantastic tool 😄

**Comment by groggemans** [comment]
Hi @r4lv

Thank you for opening this issue!
 
Seems like a valid reason to change the implementation of that function. Plus, if we can get rid of an additional dependency that's always a good thing.

I would be more then happy to review your PR!

**Comment by groggemans** [comment]
Thank you!

There was another change scheduled for 1.10.0, I might have a look at it this week. If not I'll probable tag this one as 1.9.11 by the end of the week.
