### ISSUE TITLE
Add WSL detection to os.platform

### ISSUE THREAD

**Issue by thomshouse** [ellipsis/ellipsis#105]
Hi.

I'm working on using ellipsis to rebuild my dotfiles, and I would love to add built-in support for detecting Windows Subsystem Linux (WSL) environments in the os.platform API.

I can see how to do it and can submit a PR, but before I put in the work, I wanted to see if my approach would be well-received and if there's anything else I should look out for.

My strategy would be:

- Replace `case $(uname)` with `case $(uname -rs)`
- Add cases to match against `*WSL2` and `*Microsoft` (for WSL2 and WSL1 respectively)
- Update the other cases to account for the longer `uname` output

I'd also update the docs with my PR.

Any feedback before I submit these changes?  Thanks!

**Comment by groggemans** [comment]
Hi @thomshouse 

Thank you for your interest in the project!

The suggested approach sounds good to me. As long as the longer uname output is properly handled for currently supported platforms this should be fine.

A PR would be great!

Thx!
Gertjan

**Comment by groggemans** [comment]
Closed via #108
