### ISSUE TITLE
ellipsis.sh not resolving

### ISSUE THREAD

**Issue by thomshouse** [ellipsis/ellipsis#116]
# Expected Behavior

I expect to be able to navigate to ellipsis.sh and see the Github page for ellipsis.

# Current Behavior

When I attempt to navigate to this domain, I am getting a message that the domain name does not resolve.

# Failure Information (for bugs)

ERR_NAME_NOT_RESOLVED

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Navigate to http://ellipsis.sh

**Comment by groggemans** [comment]
Hi Thom

Thank you for reporting this issue!

@zeekay is the domain owner/maintainer, so let's wait for his feedback.

**Comment by zeekay** [comment]
Should be resolving now thank you!
