### ISSUE TITLE
ellipsis.sh domain unreachable

### ISSUE THREAD

**Issue by r4lv** [ellipsis/ellipsis#117]
Dear ellipsis team,

the ellipsis.sh domain is unreachable, no DNS records show up:

https://toolbox.googleapps.com/apps/dig/#A/ellipsis.sh

Is the domain still registered? It might be a good idea to remove the references to it from the README, to make sure no one does something nasty.

Thank you for ellipsis, which has been a great tool for years, and still is!

**Comment by groggemans** [comment]
@zeekay are you still owning the domain? Can you have a look at the config? Seems like the DNS record is missing.
Let me know if I can help!

**Comment by zeekay** [comment]
Yep still have domain. Maybe issue with Netlify.

**Comment by zeekay** [comment]
So Netlify wiped all DNS records, was a bit fed up so migrated off their DNS and hosting. Got main site back up @groggemans do you happen to recall where docs.ellipsis.sh CNAME should be pointing?

**Comment by zeekay** [comment]
Ok should be resolved now.

**Comment by ozh** [comment]
Just FYI : site down
