### ISSUE TITLE
Could we get a https://ellipsis.github.io/ install URL?

### ISSUE THREAD

**Issue by tekacs** [ellipsis/ellipsis#57]
At the moment the only installation option is http://ellipsis.sh/ which is:

a) Served over HTTP
b) It can't be determined that it will match the contents of the gh-pages branch of the repo

I don't especially object to 'curl | sh' (it's hardly worse than an unsigned executable download), but being able to install over HTTPS, from what is guaranteed to be GitHub Pages would be a relief.

Could https://ellipsis.github.io/ be made to serve the contents of the gh-pages branch too?

**Comment by zeekay** [comment]
SSL enabled. HTTP will redirect to HTTPS.
