### ISSUE TITLE
Ability to pass arguments to git methods

### ISSUE THREAD

**Issue by Lugoues** [ellipsis/ellipsis#74]
It would be nice to say be able to pass `--rebase` to git.pull. I'm sure there are others that could be useful.

**Comment by groggemans** [comment]
Would you like to add params as defaults, or pass them in a custom hook for a package? Or both?

I'm rather busy at the moment, so this would end up on the todo list, which could take some time.
If you would like to work on a PR yourself, happy to help you out where needed.

**Comment by groggemans** [comment]
@Lugoues Any response? or can we close the issue?

**Comment by groggemans** [comment]
@Lugoues Closing the issue for know, please ask to reopen if you still want a solution for this.
