### ISSUE TITLE
Ability to customize repo prefix

### ISSUE THREAD

**Issue by jiri** [ellipsis/ellipsis#77]
I don't like prefixing my package repos with `dot-`, so I'd like to have a feature that enables me to set that prefix (using `$ELLIPSIS_PREFIX` presumably).

It's okay for it to default to `dot-`, for just the package name, but I find it confusing when it happens for `user/package`, since I'd expect that to correspond to the repo URL.

**Comment by zeekay** [comment]
I'm not opposed to changing this -- note that if you specify full git/http/ssh path we'll use that instead.

**Comment by jiri** [comment]
I've noticed that and I'm using it as a workaround for now 😄 

I think prefixing the repo name is confusing in itself and might be worth getting rid of altogether. It's very easy to overlook in the documentation and when using `username/repo`, it actually inserts the "prefix" into the middle of the string, which is even more confusing to me.

If you want, I can fix this and make a pull request, it should be easy enough to change :)

**Comment by zeekay** [comment]
Yeah -- makes sense. @groggemans any opinions?

**Comment by groggemans** [comment]
Seems like a good idea, always had double feelings with forcing the dot- naming scheme in the shorter notation.

It would be nice if we kept some backward compatibility though. This can be done by changing the _dot-_ with the `$ELLIPSIS_PREFIX` variable.

We can then choose to make it default to an empty string, or the current _dot-_ implementation. Either way, users can easily configure this in there `.ellipsisrc` file by providing another prefix value; 
 `ELLIPSIS_PREFIX=my_prefix`. Might be a good time to write some docs about that config file system too, I'll try to make some time this week.
