### ISSUE TITLE
confict with minificators

### ISSUE THREAD

**Issue by patocardo** [ellipsis/ellipsis#84]
YUI minificator creates a conflict with Ellipsis. It happens with the 'class' property, we gave a temporal solution by using 'class' and ['class'] in each appearence of the property, but they should renamed to keep consistance

**Comment by groggemans** [comment]
@patocardo Could it be that you opened this issue on the wrong project page?
The above explanation makes no sense to me :confused:

**Comment by patocardo** [comment]
sorry, wrong ellipsis

**Comment by groggemans** [comment]
No problem! :slightly_smiling_face:
