### ISSUE TITLE
Performance issue with env_append_path

### ISSUE THREAD

**Issue by qrevel** [ellipsis/ellipsis#91]
I'm currently profiling my zsh configuration with zprof and i found that the code used to append a path to `PATH` is more than 100 slower than [this](https://superuser.com/a/39995/870107) script:

```
pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}
```

I know it's not POSIX compliant but the `env_append_path` function took almost 7% of my zsh startup time.
```
2)    1           7.11     7.11    6.95%      7.11     7.11    6.95%  env_append_path
...
 7)    2           0.10     0.05    0.10%      0.10     0.05    0.10%  pathadd
```

**Comment by groggemans** [comment]
Interesting, probably the grep in the function that's taking much more time. But replacing it with a non posix alternative is not an option.

Skipping the duplicates check is probably an option, although I don't like it to much. (We Could add a flag for this)

In my config it only takes about 2% and 2ms per call;
```
8)    3           6.62     2.21    2.10%      6.62     2.21    2.10%  env_append_path
```

For me it would be more important to optimize the `env_init_pkg` function as it takes the most overall time in my case. (I have a lot of packages)
```
1)   30          94.57     3.15   29.96%     83.01     2.77   26.30%  env_init_pkg
```

But it will be hard to optimize these functions in a POSIX compliant way without sacrificing functionality.

**Comment by qrevel** [comment]
I understand you want to keep POSIX compliant scripts but I didn't find any optimized POSIX way to append/prepend to PATH.

I also tried to optimized env_init_pkg and I think everyting is POSIX.

**Comment by zeekay** [comment]
Maybe add an ELLIPSIS_NON_POSIX flag to enable a few optimizations? Not sure if POSIX compat is as important as Bash -- do we care about supporting anything other than some minimal Bash version?

**Comment by groggemans** [comment]
The problem is that this code will be run from the users shell. So this might be zsh, ksh, bash, dash,... So POSIX compatibility is rather important. All other ellipsis code is always run in bash, and can have bash specifics.

**Comment by groggemans** [comment]
@qrevel I found a POSIX way to optimize the append/prepend functions. It's 4 to 5x faster then the original on my machine. I'll push a PR shortly. 

Still doing some profiling on the env_init_pkg function, but I'm getting mixed results with the modifications.

**Comment by qrevel** [comment]
Do we keep this issue for env_init_pkg improvements?

**Comment by groggemans** [comment]
Good for me!

Would you like to rebase your PR? Or do I/You make a new one once I've completed some further testing/profiling on the `env_init_pkg` function?
