### ISSUE TITLE
Reinstall command?

### ISSUE THREAD

**Issue by nornagon** [ellipsis/ellipsis#97]
When I make changes in a package locally, i'd like to be able to re-run the install hooks manually. It looks like at present the only way to do that is rerun `ellipsis install`, which re-fetches the package from github. Is there a way to just re-run the install hooks and not re-fetch?

**Comment by groggemans** [comment]
Hi @nornagon,

It's currently not possible. I've been thinking about this in the past, but it's not as simple as it might look.
Some install hooks are not idempotent, and will cause trouble if called again without uninstall. Calling an uninstall hook might cleanup data you don't want to throw away.

So the question will not be if we can solve/implement this, but what strategie we should follow. Knowing that it probably won't work in all cases.

It's the same for major updates. The default pull hook will just git pull the package. But for major updates it won't always work. I've been experimenting with custom pull hooks that uninstall the package with the old uninstall hook, then pull the package and reinstall with the new install hook. (and the same for linking)

I think the best way to solve this might be to introduce a new type of hook. The "reinstall" hook. This could then be called on reinstall (and default to uninstall + install) but can be overwritten to take special actions. 

Users can already overwrite the pull hook to solve the update problems, but we might also want to improve the default so it also relinks the package during the update.

Any thoughts from your side?

**Comment by zeekay** [comment]
I'm a fan of a simple re-install hook so this can be customized per package.

**Comment by nornagon** [comment]
I think the default pull hook should definitely relink! I take your point
re: non-idempotent install steps, though IMHO writing an install to be
non-idempotent is asking for trouble.

**Comment by kevinkjt2000** [comment]
I would also love the default pull hook to relink.  Not having some of my links present after an `ellipsis pull` has bitten me before.  Most of my "installations" go into the link hook, so my "reinstalls" are done by running the link hook again.  I am not sure I see a need for a reinstall command.

**Comment by groggemans** [comment]
Thanks for all the feedback!

Did a small test with the pull hook update, but it seems to be harder than I thought it would be. It also generates a lot of noise (every package is relinked) when updating. The solution is to test if an update is available, but that makes the updates a lot slower. Also running into some other issues with the special ellipsis case (Probably why I didn't make a PR after my earlier experiments).

I'll let the results of the test sink in and take a look at the reinstall command/hook first.

**Comment by groggemans** [comment]
Closing as this was solved by #98 

Also opened #99 to follow-up on improving the update behavior.
